### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by jercle** [NaoeS/close-unmodified-tabs#2]
Hi,
I'm getting the below when using on Windows 10:
Whenever I ran the plugin, the following error appeared:
Uncaught TypeError: Cannot read property 'isPathModified' of null

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Home N
**Thrown From**: [close-unmodified-tabs](https://github.com/NaoeS/close-unmodified-tabs) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'isPathModified' of null

```
At /C:/Users/thema/.atom/packages/close-unmodified-tabs/lib/close-unmodified-tabs.coffee:22

TypeError: Cannot read property 'isPathModified' of null
    at Object.module.exports.isModifiedTab (file:///C:/Users/thema/.atom/packages/close-unmodified-tabs/lib/close-unmodified-tabs.coffee:17:9)
    at Object.module.exports.closeTab (file:///C:/Users/thema/.atom/packages/close-unmodified-tabs/lib/close-unmodified-tabs.coffee:30:31)
    at atom-workspace.subscriptions.add.atom.commands.add.close-unmodified-tabs:closeTab (file:///C:/Users/thema/.atom/packages/close-unmodified-tabs/lib/close-unmodified-tabs.coffee:11:98)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\thema\AppData\Local\atom\app-1.5.3\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -1:25 core:copy (atom-text-editor.editor.is-focused)
     -1:23.7.0 core:paste (atom-text-editor.editor.is-focused)
     -1:20.8.0 core:cut (atom-text-editor.editor.is-focused)
     -1:18.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:15.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:15.2.0 core:delete (atom-text-editor.editor.is-focused)
     -1:14.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:14 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:13.2.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  9x -1:08.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:04.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:02.7.0 close-unmodified-tabs:closeTab (atom-text-editor.editor.is-focused)
     -0:10.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 close-unmodified-tabs:closeTab (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.24
close-unmodified-tabs, v1.0.0
color-picker, v2.1.1
emmet, v2.4.1
file-icons, v1.6.16
minimap, v4.19.0
pigments, v0.24.2
spacegray-atom-dark-syntax, v1.1.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by NaoeS** [comment]
Thanks @jERCle,
Start an investigation of the this problem.

**Comment by NaoeS** [comment]
There was a problem with the confirmation of the git repository.
Already was fixed code!

**Comment by jercle** [comment]
Ok fantastic
